name: Create issue when rule is degraded

on:
  workflow_dispatch:
    inputs:
      rule_result_name:
        description: 'The rule result name'
        required: true
        type: string
      entity_link:
        description: 'A link to the evaluated entity'
        required: true
        type: string
      runId:
        description: "The run's unique id"
        required: true
        type: string

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps: 
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira issue
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: POR
        issuetype: Task
        summary:  "Automation task - degraded rule result: ${{ inputs.rule_result_name }}"
        description: |
          This task was created by a Port automation, due to the degradation of rule result ${{ inputs.rule_result_name }}. See evaluated entity: ${{ inputs.entity_link }}.
    
    - name: Log issue creation
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: PATCH_RUN
        link: ${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create.outputs.issue }}
        runId: ${{ inputs.runId }}
        logMessage: |
           Jira issue created! âœ…
           
           The issue id is: ${{ steps.create.outputs.issue }}
